add solution for modal
js-tasks-ru/htmlcss-20210708_artur-mingazhov pull request #8
Opened 2021-07-21 07:14 UTC by Arthur-Ming

2021-07-21 07:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-23 14:47 UTC, GSemikozov requested changes

2021-07-23 14:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.popup::after {
вместо этого на самом блоке достаточно задать фон через rgba

2021-07-23 14:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +   background: #fff;
заберем из переменных

2021-07-23 14:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +   width: 35%;
на мобилке боюсь это будет слишком маленькая модалка)

2021-07-23 14:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.popup__close::before,
здесь надо использовать иконку из фигмы. Но - можем сделать это в другом ПР с svg-спрайтом

2021-08-22 05:54 UTC, closed without merging