add solution for calendar
js-tasks-ru/htmlcss-20210708_artur-mingazhov pull request #9
Opened 2021-07-22 08:52 UTC by Arthur-Ming

2021-07-22 08:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-23 14:49 UTC, GSemikozov requested changes

2021-07-23 14:49 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +   padding-top: 24px;
определяем поведение внешнее, поэтому - margin

2021-07-23 14:49 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +   color: #90a0b7;
здесь и в других местах цвета лучше забирать из переменных

2021-07-24 13:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-24 14:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-24 14:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-24 14:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-24 14:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-24 15:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-22 05:54 UTC, closed without merging